version: '3.3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: database_password
      POSTGRES_USER: student
      POSTGRES_DB: lab_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  project-data:
