version: 2

jobs:
  build:
    working_directory: ~/circleci-students-lab
    docker:
    - image: circleci/python:3.6.4
    #   environment:
    #     DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    # - image: circleci/postgres:11
    #   environment:
    #     POSTGRES_USER: root
    #     POSTGRES_DB: test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: install dependencies
          command: |
            pip install -U pip
            pip install -r requirements-dev.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: run linting
          command: |
            python -m flake8
      # - run:
      #     name: run tests
      #     command: |
      #       python -m pytest
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: tr1
