# Generated by Django 2.2.1 on 2019-06-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering_date', models.DateTimeField(auto_now_add=True)),
                ('use_default_address', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('Paypal', 'Paypal'), ('Card', 'Card'), ('Cash', 'Cash'), ('Qiwi', 'Qiwi')], default='Card', max_length=25)),
                ('delivery_method', models.CharField(choices=[('Standart', 'Standart delivery'), ('Next day', 'Next day delivery')], default='Standart', max_length=25)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('In progress', 'In progress'), ('Complete', 'Complete')], default='In progress', max_length=25)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
